### ISSUE TITLE
Why the card is blank?

### ISSUE THREAD

**Issue by InspecteurKepler** [Dielee/localToDo-card#1]
Hello, first of all I would like to congratulate you for this project because it is the type of task list I was looking for for Home Assistant.

I have a problem with the configuration of the card, I have currently configured the docker, I have added the right port and IP address but when I want to add the card, it is completely empty. Am I missing something?

I also didn't understand how to add the script to add the spots, where should I put the script? In which file?
![image](https://user-images.githubusercontent.com/45036197/176556095-6b2d9991-5356-4c57-950c-f9e03a77272a.png)

**Comment by Dielee** [comment]
Hello! 
What does the browser console say ?
And please show me your `sensor.to_do_list`  attributes.

**Comment by andjohansen** [comment]
I have the same issue. 
This is my sensor.to_do_list
items: 
settings: 
language: English
persons:
  - Anders
  - Mette

**Comment by andjohansen** [comment]
Uncaught (in promise) ReferenceError: filterLable is not defined
    at TodoistCard.render (localtodo-card.js:508:25)
    at TodoistCard.update (lit-element.js?module:6:649)
    at TodoistCard.performUpdate (reactive-element.js?module:6:5684)
    at TodoistCard.scheduleUpdate (reactive-element.js?module:6:5283)
    at TodoistCard._$Ej (reactive-element.js?module:6:5182)

**Comment by Dielee** [comment]
Thanks for the error! 
Can you please show me your sensor data in HA ? I will look into the code later today.

**Comment by andjohansen** [comment]
Found the problem.
On line 508 the Lablefiltre wasn't defined.
Put in var Lablefiltre and it worked.

**Comment by Dielee** [comment]
Please try the new release!
